routes:
  # GET request to /cp/addons/addon-name using the index method
  /:
    as: addons.menu_editor
    uses: index
  /json: BigKahunaController@json
  /allpages: BigKahunaController@allpages
  # POST request to /cp/addons/addon-name/save using the save method
  post@save: BigKahunaController@save
