routes:
  # GET request to /cp/addons/addon-name using the index method
  /:
    as: addons.menu_editor
    uses: index
  /json: MenusController@json
  # POST request to /cp/addons/addon-name/save using the save method
  post@save: MenusController@save
